#server:
#  port: 8083
#
#spring:
#  application:
#    name: gateway-api
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/application/**
#        - id: notification-service
#          uri: lb://notification-service
#          predicates:
#            - Path=/notifications/**
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-api

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      uri: http://config-server:8888
